<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-L2504" ignored="0" name="GET Feeds - Change in Liabilities" tests="13" failures="7" timestamp="14 Jun 2021 19:29:27 GMT" time="1124.451" errors="0">
  <testcase name="testGetNotificationsForChangeInLiabilities" time="134.62" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="79.45" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.insights.yodleeApi.utils.NotifiedInsightsDataValidation.verifyGeneratedInsightsV2(NotifiedInsightsDataValidation.java:111)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="66.137" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.324" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="68.809" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="65.859" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.198" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="97.941" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="66.908" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.766" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="68.849" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="67.172" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.61" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
</testsuite> <!-- GET Feeds - Change in Liabilities -->
