<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-L2504" ignored="0" name="New Bill" tests="17" failures="15" timestamp="18 May 2021 14:40:50 GMT" time="646.113" errors="0">
  <testcase name="@AfterMethod prepareAutomationReport" time="0.0" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.insights.yodleeApi.utils.InsightsHelper.printSummaryOfTests(InsightsHelper.java:1966)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.prepareAutomationReport(TestGetInsightsForNewBill.java:306)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod prepareAutomationReport -->
  <testcase name="testGetNotificationsForNewBill" time="41.052" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill"/>
  <testcase name="testGetNotificationsForNewBill" time="43.011" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill"/>
  <testcase name="testGetNotificationsForNewBill" time="41.548" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="24.693" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="29.751" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="45.975" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  30 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  30 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="24.709" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:273)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="39.997" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="41.2" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="40.196" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:273)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="40.815" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="44.96" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="40.991" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:273)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="40.082" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="24.754" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="24.532" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
  <testcase name="testGetNotificationsForNewBill" time="39.702" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  15 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  15 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNewBill.testGetNotificationsForNewBill(TestGetInsightsForNewBill.java:299)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNewBill -->
</testsuite> <!-- New Bill -->
