<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities" tests="13" time="1113.643" ignored="0" failures="6" timestamp="14 Jun 2021 20:37:45 GMT" skipped="0" hostname="IN-L2504" errors="1">
  <testcase name="testGetNotificationsForChangeInLiabilities" time="134.620" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.610" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="66.137" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="79.450" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.insights.yodleeApi.utils.NotifiedInsightsDataValidation.verifyGeneratedInsightsV2(NotifiedInsightsDataValidation.java:111)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="97.941" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="66.908" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="68.809" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.324" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="67.172" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.198" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="68.849" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
  <testcase name="testGetNotificationsForChangeInLiabilities" time="99.766" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities"/>
  <testcase name="testGetNotificationsForChangeInLiabilities" time="65.859" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities">
    <failure type="java.lang.AssertionError" message="There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time">
      <![CDATA[java.lang.AssertionError: There is no CHANGE_IN_LIABILITIES insight generated in the given scheduled time
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities.testGetNotificationsForChangeInLiabilities(TestGetInsightsForChangeInLiabilities.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForChangeInLiabilities -->
</testsuite> <!-- com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForChangeInLiabilities -->
