<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" tests="30" time="1938.334" ignored="0" failures="18" timestamp="26 May 2021 12:25:37 GMT" skipped="0" hostname="IN-L2504" errors="5">
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.833" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.073" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.880" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.726" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.825" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  6 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  6 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.821" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.008" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  1 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  1 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.805" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.752" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.850" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.698" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.722" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.805" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.988" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  1 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  1 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="prepareAutomationReport" time="0.000" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.insights.yodleeApi.utils.InsightsHelper.printSummaryOfTests(InsightsHelper.java:1966)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.prepareAutomationReport(TestGetInsightsForUpcomingSubscription.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- prepareAutomationReport -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.862" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.036" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.747" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.727" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.855" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.801" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.971" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.836" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.110" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.752" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.762" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.701" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.708" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.813" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at org.testng.Assert.fail(Assert.java:94)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.867" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
</testsuite> <!-- com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription -->
